# Caminata aleatoria en 1D

La posición de la partícula se representa con $x\in\mathbb{Z}$. 
En $t=0$ la partícula está en el origent $x=0$

In [1]:
x=0

0

## ¿Cómo generamos brincos aleatorios?

In [2]:
?rand

search: rand randn rand! randn! randexp randperm randjump randexp! randbool



```
rand([rng], [S], [dims...])
```

Pick a random element or array of random elements from the set of values specified by `S`; `S` can be

  * an indexable collection (for example `1:n` or `['x','y','z']`), or
  * a type: the set of values to pick from is then equivalent to `typemin(S):typemax(S)` for integers (this is not applicable to `BigInt`), and to $[0, 1)$ for floating point numbers;

`S` defaults to `Float64`.


In [12]:
rand(1:10)

3

In [40]:
rand([-1 1])

-1

### Cómo utilizamos `rand()` para cambiar la posición en $\pm1$?

In [35]:
rand(Bool) ? δ = 1 : δ = -1

x += δ

-2

In [34]:
x

-1

Queremos hacer este procedimiento 100 veces:

In [37]:
N=100
for i in 1:N
    rand(Bool) ? δ = 1 : δ = -1 
    x += δ
end
println(x)

In [39]:
x

-18

Crearemos una función que actualicé la posición de la partícula:

In [56]:
function caminando( N, x_inicial=0)
    r=x_inicial
    for i in 1:N
        #rand(Bool) ? δ = 1 : δ = -1
        δ=rang([-1 1])  #Lo actualicé
        r += δ
        #println(r)
    end
    return r
end

caminando (generic function with 2 methods)

In [57]:
x=caminando(100)

2

In [66]:
typeof(x)

Int64

## Visualizar



Un número no nos dice mucho. Vamos a graficar toda la trayectoria. **¿Qué necesitamos para hacer gráficas?**

In [58]:
using Plots #Pkg.add("Plots.jl")
plotly()

Plots.PlotlyBackend()

In [65]:
plot([1 2 3 4], [1 2 3 4], m=:diamond, ms=5, color="red")

Muchos pares de números.

Modifiquemos nuestra función `caminando()` para que nos de la posición en cada paso.

In [73]:
function caminando2(N,x_inicial=0)
    r=x_inicial
    x=[r]
    for i in 1:N-1
        #rand(Bool) ? δ = 1 : δ = -1
        δ=rand([-1 1])     #Creo que es más eficiente así
        r += δ
        push!(x,r)
    end
    return x

end


caminando2 (generic function with 2 methods)

In [74]:
x=caminando2(10,10)

10-element Array{Int64,1}:
 10
  9
 10
  9
  8
  7
  6
  5
  4
  3

In [78]:
x=caminando2(100,10)
plot(x, shape=:circle, ms=1, label="Posición del caminante",xlabel="# de pasos")

## Guardar y leer datos
A veces es útil guardar o leer datos de archivos.

Vamos a usar las funciones `writedlm()` y `readdlm()`
¿Cómo funcionan?

In [79]:
?writedlm

search: writedlm



```
writedlm(f, A, delim='\\t')
```

Write `A` (a vector, matrix or an iterable collection of iterable rows) as text to `f` (either a filename string or an `IO` stream) using the given delimiter `delim` (which defaults to tab, but can be any printable Julia object, typically a `Char` or `AbstractString`).

For example, two vectors `x` and `y` of the same length can be written as two columns of tab-delimited text to `f` by either `writedlm(f, [x y])` or by `writedlm(f, zip(x, y))`.


In [90]:
#Pkg.add("DelimitedFiles")
#using DelimitedFiles
t=collect(1:100)
writedlm("Datos_caminante.dat", [t x])

In [81]:
zeros(10, 10)

10x10 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [91]:
?readdlm

search: readdlm readdir readandwrite



```
readdlm(source, delim::Char, T::Type, eol::Char; header=false, skipstart=0, skipblanks=true, use_mmap, ignore_invalid_chars=false, quotes=true, dims, comments=true, comment_char='#')
```

Read a matrix from the source where each line (separated by `eol`) gives one row, with elements separated by the given delimiter. The source can be a text file, stream or byte array. Memory mapped files can be used by passing the byte array representation of the mapped segment as source.

If `T` is a numeric type, the result is an array of that type, with any non-numeric elements as `NaN` for floating-point types, or zero. Other useful values of `T` include `ASCIIString`, `AbstractString`, and `Any`.

If `header` is `true`, the first row of data will be read as header and the tuple `(data_cells, header_cells)` is returned instead of only `data_cells`.

Specifying `skipstart` will ignore the corresponding number of initial lines from the input.

If `skipblanks` is `true`, blank lines in the input will be ignored.

If `use_mmap` is `true`, the file specified by `source` is memory mapped for potential speedups. Default is `true` except on Windows. On Windows, you may want to specify `true` if the file is large, and is only read once and not written to.

If `ignore_invalid_chars` is `true`, bytes in `source` with invalid character encoding will be ignored. Otherwise an error is thrown indicating the offending character position.

If `quotes` is `true`, column enclosed within double-quote (") characters are allowed to contain new lines and column delimiters. Double-quote characters within a quoted field must be escaped with another double-quote.  Specifying `dims` as a tuple of the expected rows and columns (including header, if any) may speed up reading of large files.  If `comments` is `true`, lines beginning with `comment_char` and text following `comment_char` in any line are ignored.

```
readdlm(source, T::Type; options...)
```

The columns are assumed to be separated by one or more whitespaces. The end of line delimiter is taken as `n`.

```
readdlm(source, delim::Char, T::Type; options...)
```

The end of line delimiter is taken as `n`.

```
readdlm(source, delim::Char, eol::Char; options...)
```

If all data is numeric, the result will be a numeric array. If some elements cannot be parsed as numbers, a cell array of numbers and strings is returned.

```
readdlm(source, delim::Char; options...)
```

The end of line delimiter is taken as `n`. If all data is numeric, the result will be a numeric array. If some elements cannot be parsed as numbers, a cell array of numbers and strings is returned.

```
readdlm(source; options...)
```

The columns are assumed to be separated by one or more whitespaces. The end of line delimiter is taken as `n`. If all data is numeric, the result will be a numeric array. If some elements cannot be parsed as numbers, a cell array of numbers and strings is returned.


In [92]:
r=readdlm("Datos_Caminante.dat")

100x2 Array{Float64,2}:
 -1.0    1.0
 -2.0    2.0
 -1.0    3.0
 -2.0    4.0
 -3.0    5.0
 -4.0    6.0
 -3.0    7.0
 -2.0    8.0
 -3.0    9.0
 -4.0   10.0
 -5.0   11.0
 -4.0   12.0
 -5.0   13.0
  ⋮         
  7.0   89.0
  6.0   90.0
  5.0   91.0
  4.0   92.0
  3.0   93.0
  2.0   94.0
  3.0   95.0
  2.0   96.0
  3.0   97.0
  4.0   98.0
  3.0   99.0
  4.0  100.0

In [103]:
r[1,:]

1x2 Array{Float64,2}:
 -1.0  1.0

In [104]:
plot(r[:,2],r[:,1])

### Ejercicio

1. Utiliza un `for` para dibujar 100 caminos con 100 pasos cada uno. Para hcerlo, primero crea un plot vacío con el nombre p y luego dibuja los caminantes. Al final, muestra p
2. ¿Qué observas? ¿Cómo crece la nube en función del tiempo?
3. ¿ En la gráfica, los caminos se sobreponen., así que no se puede er cuántos caminantes pasaron por un punto dad en cada paso. En un paso dado ¿qué harías para ver esto?

In [121]:
p = plot( shape=:circle, ms=1, label="Posiciones de los caminantes", xlabel="# de pasos")
for i in 1:100
    caminantes=caminando2(100) 
    plot!(caminantes, shape=:circle, ms=0.5, title="Posiciones de los caminantes", xlabel="# de pasos", leg= false)
end
t=0:100
plot!(t,sqrt(t),lw=:2, color="red")
plot!(t,-sqrt(t),lw=:2, color="red")
display(p)

In [119]:
plot!(t,sqrt(t),lw=:2, color="red")
plot!(t,-sqrt(t),lw=:2, color="red")
display(p)

In [125]:
t=collect(t)
t.^(0.5)

101-element Array{Float64,1}:
  0.0    
  1.0    
  1.41421
  1.73205
  2.0    
  2.23607
  2.44949
  2.64575
  2.82843
  3.0    
  3.16228
  3.31662
  3.4641 
  ⋮      
  9.43398
  9.48683
  9.53939
  9.59166
  9.64365
  9.69536
  9.74679
  9.79796
  9.84886
  9.89949
  9.94987
 10.0    