# Más métodos Monte Carlo
Se le llama método Monte Carlo a todo aquel algoritmo computacional que usa números aleatorios como herramienta principal para resolver problemas. Hoy vamos a resolver el siguiente problema usando números aleatorios.


## Problema del cumpleaños

> Si tenemos un grupo de 23 personas. ¿Cuál es la probabilidad de que al menos dos personas del grupo cumplan años el mismo día?

Para resolver este problema usaremos el poder de la computadora. Esto se logrará de la siguiente manera: 

1. Generaremos una lista aleatoria con 23 fechas de cumpleaños

2. Escribiremos un código capaz de decirnos si se repite alguna fecha

3. Crearemos una función que repita este proceso un número arbitrario de veces y nos diga cuántas veces se repitió al menos un cumpleaños

4. Ahora ya podemos calcular la probabilidad ¿Cómo le hacemos?

## Caminantes aleatorios

Una caminata aleatoria es un objeto matemático que describe la trayectoria de una partícula que cambia de dirección de manera aletoria a cada paso. El ejemplo más sencillo es el movimiento en una dimensión con una longitud de paso constante; pensemos que se mueve en la línea recta y se mueve una unidad a la derecha o a la izquierda (+1 o -1) en cada paso. Otro ejemplo incluye el camino trazado por una partícula muy pequeña inmersa en un líquido o gas (**Movimiento Browniano**), el camino de búsqueda de forraje por un animal, la fluctuación del valor de las acctions y el estado financiero de un apostador se pueden modelar usando caminantes aleatorios; incluso si realmente no son completamente aleatorios. 

Aplicación en muchas ramas de la ciencia: ecología, psicología, ciencias de la computación, física, química, biología y economía.

### Modelando
Para modelar un sistema físico debemos hacer ciertos simplificaciones, 

* Modelaremos la interacción del fluido con la partícula mediante impactos aleatorios sobre la partícula,
* Suponemos que, debido a los impactos, la partícula se mueve en brincos,
* Los impactos se dan en tiempos regulares, la distancia temporal entre impactos consecutivos es constante,
* Supondremos que los brincos son de distancia constante y se mueve en una cuadrícula.

### Caminata aleatoria en 1D

La posición de la partícula se representa con $\{x | x \in \mathbb{Z}\}$; se mueve sobre la recta numérica. Por simplicidad vamos a suponer que en $t=0$ la partícula está en el origen $x=0$.

**¿Cómo generamos pasos aleatorios a la derecha o a la izquierda con igual probabilidad?**



Ahora podremos hacer nuestra primera caminata. 

**Vamos a escribir una función que tome un argumento, t, y mueva la partícula t pasos consecutivos**

1. Cree una función llamada `pasos(t)` que imprima a pantalla las posiciones del caminante.

2. Modifique la función para que guarde las posiciones en un vector y lo regrese como resultado.

### Visualización

Ahora vamos a hacer dibujos.

1. Crea una arreglo llamado  `caminante` con 20 pasos.

2. Usa `plot()` o `scatter()` para dibujar la trayectoria del caminante

3. Crea 5 caminantes más y dibuja sus trayectorias en una sola gráfica.

### Nube de Caminantes

1. Usa un `for` para crear 100 caminantes con 100 pasos y dibújalos en la misma gráfica. 

*Tip: Guarda una gráfica vacía sin leyenda (`leg=false`) en una variable, `p`, y agrega las gráficas usando `plot!()`. Al final debes mostrar la gráfica con el comando `display(p)`*

2. ¿Qué observas? ¿Cómo crece la nube en función de los pasos? 

3. ¿Cuántos caminantes coninciden en el mismo punto al mismo tiempo?

### Guardar los datos

1 Guarda los datos que se generaron con
```julia
using DelimitedFiles  # paquete para escribir y leer datos
writedlm("archivo.dat", v)
```
donde el primer argumento es el nombre del archivo que se escribirá, y `v` es la variable a guardar.

In [1]:
using DelimitedFiles


In [7]:
v=rand(20)
b= rand(20)
writedlm("prueba2.dat",[v b])

In [3]:
;ls

13_may_MonteCarlo_pi.ipynb
15_May_MonteCarlo_Cumple_Caminante.ipynb
1_Abril_Ejercicios.ipynb
27_Mar_Iteraciones.ipynb
29_Abril_LeyendoDatos_HuellaEco.ipynb
6_May_Graficas_3D.ipynb
8-10-25_Abr_GraficasyDatos.ipynb
8_Abr_GraficasyDatos.ipynb
circulos.jpg.png
Control_de_flujo.ipynb
Funciones.md
Jupyter_notebooks.ipynb
Mexico_gha_per_person.csv
Mexico_numeros_tierras.csv
prueba.dat
Usando_la_REPL.md
Variables.md


In [8]:
;cat prueba.dat

0.5462383059891918	0.6432875715743285
0.6755854572269673	0.07073530929564331
0.9043583457278734	0.7071480080783228
0.3834041476711998	0.15630867338502163
0.3813243523979033	0.0908223475689025
0.34305882413767663	0.30504595889512376
0.9962654275169867	0.5643744782103659
0.263754726972518	0.2589419736800238
0.33276004875797494	0.5266168623456804
0.4507583783871414	0.6542959556227339
0.9363251171510318	0.7890419796755004
0.3705024881527619	0.43100790749178053
0.8391612970132352	0.2942407471516655
0.32290673808298	0.4769457945913833
0.05545847202258991	0.13688730441192654
0.18368157342035896	0.38601965032663244
0.4161111478878652	0.239907583560937
0.1280117544068411	0.6529473279977527
0.2568132968230237	0.7330871499405767
0.942869469581179	0.942365600747741


In [17]:
m = readdlm("prueba.dat")

20×2 Array{Float64,2}:
 0.337553  0.781462 
 0.175234  0.322167 
 0.329415  0.638491 
 0.596347  0.421733 
 0.57114   0.787567 
 0.597402  0.248778 
 0.851759  0.980984 
 0.109154  0.0677692
 0.333515  0.497146 
 0.817964  0.717804 
 0.195649  0.188016 
 0.217308  0.659262 
 0.663638  0.312656 
 0.111544  0.384446 
 0.597544  0.983929 
 0.328689  0.248945 
 0.803144  0.584554 
 0.289888  0.0905905
 0.862908  0.550854 
 0.512215  0.0935989

In [10]:
?writedlm

search: writedlm



```
writedlm(f, A, delim='\t'; opts)
```

Write `A` (a vector, matrix, or an iterable collection of iterable rows) as text to `f` (either a filename string or an `IO` stream) using the given delimiter `delim` (which defaults to tab, but can be any printable Julia object, typically a `Char` or `AbstractString`).

For example, two vectors `x` and `y` of the same length can be written as two columns of tab-delimited text to `f` by either `writedlm(f, [x y])` or by `writedlm(f, zip(x, y))`.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = [5; 6; 7; 8];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y])
       end

julia> readdlm("delim_file.txt", '\t', Int, '\n')
4×2 Array{Int64,2}:
 1  5
 2  6
 3  7
 4  8

julia> rm("delim_file.txt")
```


In [16]:
open("prueba.dat","w") do io
    writedlm(io,[b v])
end

20-element Array{Float64,1}:
 0.781461822378293  
 0.32216657116231406
 0.6384907490366114 
 0.42173327602011823
 0.7875674031385929 
 0.2487781287401738 
 0.9809839993248408 
 0.06776915362888669
 0.49714574153831514
 0.7178040359321627 
 0.18801580011066354
 0.659261704914544  
 0.31265640768282355
 0.3844457150061831 
 0.9839293926813109 
 0.24894471276171548
 0.5845542126029835 
 0.09059050035338645
 0.5508536098003185 
 0.09359894960220205